### ISSUE TITLE
object_hook() missing 1 required positional argument

### ISSUE THREAD

**Issue by davinerd** [JarryShaw/PyPCAPKit#37]
**Describe the bug**
Function `object_hook()` requires a positional argument

**System information**
 - OS Version: ubuntu 19.04
 - Python Version: 3.7
 - Python Implementation: pip

**Traceback stack**
```
$ pcapkit-cli file.pcap --format json
Traceback (most recent call last):
  File "/home/me/test/venv/bin/pcapkit-cli", line 8, in <module>
    sys.exit(main())
TypeError: object_hook() missing 1 required positional argument: 'o'
```

**Expected behavior**
Packet in JSON format

**Comment by JarryShaw** [comment]
Ahhh… due to my upgrade of the underlying formatting package `DictDumper`, the current version of `PyPCAPKit` is **NOT** compatible.

Please rewind and pin the version of `DictDumper` to `~=0.7.0`.

I’m right now actively updating `PyPCAPKit`; new version shall be released with better support in a short time.

**Comment by JarryShaw** [comment]
Ahhh… due to my upgrade of the underlying formatting package `DictDumper`, the current version of `PyPCAPKit` is **NOT** compatible.

Please rewind and pin the version of `DictDumper` to `~=0.7.0`.

I’m right now actively updating `PyPCAPKit`; new version shall be released with better support in a short time.

**Comment by JarryShaw** [comment]
Issue fixed as we upgrade DictDumper dependency in version 0.15.0

Thx for reporting to us.
